version: '3.13.1'

services:
    web:
       build: str
       command: gunicorn --bind 0.0.0.0.8000 Home.wsgi:application
       volumes:
          - .:/app
       ports:
          - "8000:8000"
       env_file:
          - .env
       depends_on:
          - redis
    redis:
       image: redis.alpine