# Generated by Django 5.2.7 on 2025-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VIE0hWTHKrzI0fDMzN4lLCBRFu6uNOAc', editable=False, max_length=32, unique=True),
        ),
    ]
