# Generated by Django 5.2.7 on 2025-10-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VWTJBnJ6wdM3nl8WQIUMvQyM9HQ801Bq', editable=False, max_length=32, unique=True),
        ),
    ]
