# Generated by Django 5.1.1 on 2025-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='EIKFl5coyADvV1aCvPRt8XhCW3ze1rMI', editable=False, max_length=32, unique=True),
        ),
    ]
